# fly.toml app configuration file generated for inclusive-ai on 2023-08-21T03:20:43-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "inclusive-ai"
# primary_region = "sjc"

[env]
PRIMARY_REGION = "sjc"

[build]

#[http_service]
#  internal_port = 8080
#  force_https = true
#  auto_stop_machines = false
#  auto_start_machines = false
#  min_machines_running = 0
#  processes = ["app"]

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0

  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
